[book]
authors = ["Vsevolod Zubarev"]
src = "src"
title = "Введение в Русский Информ"
description = "Учебник и справка по Русскому Информу."
language = "ru"

[output.html.search]
enable = false

[output.linkcheck2]
follow-web-links = false
